# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiddify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VidInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_img', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=200)),
                ('country_flag', models.CharField(max_length=200)),
                ('vid_poster', models.CharField(max_length=200)),
                ('vid_src', models.CharField(max_length=200)),
                ('thumb_img', models.CharField(max_length=200)),
            ],
        ),
    ]
