# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiddify', '0002_vidinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='vidinfo',
            name='src_type',
            field=models.CharField(default=b'some string', max_length=200),
        ),
        migrations.AddField(
            model_name='vidinfo',
            name='track_kind_first',
            field=models.CharField(default=b'some string', max_length=200),
        ),
        migrations.AddField(
            model_name='vidinfo',
            name='track_kind_second',
            field=models.CharField(default=b'some string', max_length=200),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
